name: Build and deploy
on: 
  push: 
    branches:
      - master

jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@main
      - name: set up node.js
        uses: actions/setup-node@main
        with:
          node-version: 16.x
      - name: cache node_modules
        uses: actions/cache@v1
        with: 
          path: node_modules
          key: $-build-$${hashFiles('**/package-lock.json')}
          restore-keys: |
            $-build-$-build
      - name: install devDependencies
        run: npm install
      - name: build
        run: npm run
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_ACTIONS_TOKEN }}
          publish_dir: ./dist